### ISSUE TITLE
imptcp input parameter "notifyonconnectionclose" misspelled

### ISSUE THREAD

**Issue by qha** [rsyslog/rsyslog-website#33]
On http://www.rsyslog.com/doc/v8-stable/configuration/modules/imptcp.html the input parameter "notifyonconnectionclose" is described as "servernotifyonconnectionclose".

**Comment by rgerhards** [comment]
Thanks for the report. All doc originates from the rsyslog-doc project. If you like, you can fix it there and create a PR: https://github.com/rsyslog/rsyslog-doc

**Comment by qha** [comment]
Ok, I will try to make time for that.

**Comment by qha** [comment]
My commit that fixes this appears to have been merged.
