### ISSUE TITLE
Config builder doesn't seem to work on FF or Chrome

### ISSUE THREAD

**Issue by munntjlx** [rsyslog/rsyslog-website#48]
I tried using the config builder, but it never adds my rules, or changes. Simply goes back to blank screen like I had never typed in anything.

**Comment by ardentmusician** [comment]
Having the same issue on FireFox 68.0.2 (64-bit, Windows).

**Comment by kswtch** [comment]
Can confirm.

```
$ uname -r
4.19.57-gentoo

$ uname -m
x86_64

$ firefox-bin -v
Mozilla Firefox 68.0.2

$ google-chrome-stable --version
Google Chrome 76.0.3809.100
```

**Comment by malro57** [comment]
same on:
- chrome Version 77.0.3865.120 (Build officiel) (64 bits)
- edge Version 44.18362.387.0
- internet explorer Version11.418.18362.0

**Comment by gadgetusaf** [comment]
having the same issue

**Comment by pedrom34** [comment]
Is there a way to make it work? Like using another browser?

**Comment by rgerhards** [comment]
It is probably broken. I guess we will take it offline as it would require a major overhaul.

@alorbach what do you think?

**Comment by alorbach** [comment]
It works on my Chrome (Windows) and even FireFox (Ubuntu 18) for me. 
You maybe need to disable ADBLOCKER on rsyslog.com ;)

Although this interface should be rewritten using Jquery UI. 

If anybody has this problem, please use the INSPECT function from your browser and post the console results.

**Comment by pedrom34** [comment]
[Here is my export](https://github.com/rsyslog/rsyslog-website/files/3977899/console-export-2019-12-18_10-35-58.txt)

**Comment by pedrom34** [comment]
I can also provide exports with chrome or edge, on Linux or Windows 10...

**Comment by cengbrecht** [comment]
Can confirm it does not work on Edge, Chrome, or FF with Adblock set to allow, or no extensions at all on Edge.

**Comment by alxwolf** [comment]
Seems like you're using cross-site cookies being blocked by "modern" browsers (here: Chrome 79.0.3945.130 on macOS)
[www.rsyslog.com-1579677996921.log](https://github.com/rsyslog/rsyslog-website/files/4095768/www.rsyslog.com-1579677996921.log)

**Comment by alorbach** [comment]
@gittyhub2 All these warnings come from the jquery version being used (Should be reviewed for update) and not from the config builder itself. 

But I found the reason why the config builder did not appear to work anymore, a plugin used by our cms system was broken. The config builder depends on this plugin, so it could not store the config objects in the browser session anymore. 

The config builder should be working again now, can you guys confirm?

**Comment by pedrom34** [comment]
YES!

**Comment by alxwolf** [comment]
@alorbach nice, thanks! Works like a charm under Chrome / Windows 10. will test macOS later.

**Comment by sarvesh-lad** [comment]
I think its down again, i tried building some config and keeps reverting to the basic empty one.

Console shows error loading below two resources:

1. https://www.rsyslog.com/wp-content/themes/zakra/base-min.css
2. https://www.rsyslog.com/wp-content/themes/zakra/images/navigate_plus.png

**Comment by spp2** [comment]
Hi, 

@alorbach Maybe you could use your magic wand again, the wizard is down today ;-)

(For reference https://www.rsyslog.com/rsyslog-configuration-builder/ )

Btw half of the page is taken by redundant information:
 title, menus, the huge Ad, next title, sub title, explanations
Each modification needs the page to be scrolled down every time.
A great enhancement would be to put the wizard in front of everything.

That set aside, bugs are behind nearly all buttons; Add Ruleset, Add Filter, ... 
And there is a third 404 :
https://www.rsyslog.com/wp-content/themes/zakra/images/navigate_minus.png

**Comment by sandrotanner** [comment]
Can confirm it is down again. No session storage or cookie at all besides PHPSESSID

**Comment by alorbach** [comment]
The settings are temporary stored in php session object (server side), so they live as long as the php session lives. I could not reproduce any problem with the configuration builder. Perhaps you can explain what is not working at your end @sandrotanner  ?

**Comment by sandrotanner** [comment]
Ah, makes sense.

It's funny: now that I wanted to go back to report the errors, it works. Not only that, but the data I entered earlier today appears. Before I had the same problem as stated in the original issue:

> I tried using the config builder, but it never adds my rules, or changes. Simply goes back to blank screen like I had never typed in anything.

**Comment by sandrotanner** [comment]
I have to correct my previous statement:
- The things I did earlier today are there.
- New things I add don't appear (even with ctrl + F5)

So maybe there is a long delay / queue on the server side?

Also it says: 
`This configuration was generated on '2021-10-18 12:20:27'`
even though I made changes at 12:25 (and clicked the "update configuration" button).

**Comment by sandrotanner** [comment]
Right now the new changes are visible and it says `This configuration was generated on '2021-10-18 12:32:26'`

So it seems there is a 12 minute delay between the input of data and the display of the config file.

**Comment by alorbach** [comment]
@sandrotanner Maybe this is a browser caching issue, can you disable caching for testing (In Chrome, see screenshot)?
![image](https://user-images.githubusercontent.com/1675286/137733242-395bd950-3d3c-4a32-99af-d1046c9ac386.png)

**Comment by sandrotanner** [comment]
Thanks. I already had the devtools open and the checkbox ticked. I also used ctrl + F5 to refresh, which does the same.

TRacking protection and ad block are also off.

**Comment by alorbach** [comment]
Allright I will close this issue then.

**Comment by sandrotanner** [comment]
Sorry I worded that strangely. I did use no-cache already and it did not work anyway.

**Comment by malavolti** [comment]
Hi to all of you,

today I wanted to try Rsyslog Configuration Builder, but it doesn't work.

I'm using Google Chrome 97 (without AdBlock and with Disabled Cache) and FireFox 91.5.

Can you help me, please?

Thank you so much!
