### ISSUE TITLE
Download links are 404

### ISSUE THREAD

**Issue by lukenowak** [rsyslog/rsyslog-website#50]
Hello,

After navigating to https://www.rsyslog.com/downloads/download-v8-stable/ and clicking on download link it results 404 for https://www.rsyslog.com/files/download/rsyslog/rsyslog-8.2006.0.tar.gz

Same happens for all links in https://www.rsyslog.com/downloads/download-other/ (eg. http://www.rsyslog.com/download/files/download/rsyslog/rsyslog-8.2004.0.tar.gz )

**Comment by rgerhards** [comment]
Thx dir Info. It's fixed now.
